// lib/state/researchAtoms.ts

import { atom } from "jotai"

import type { ResearchStage } from "@/app/actions/researchAgentOrchestrator"

// --- Client-Friendly Data Structures ---

/**
 * Document status tracking enum for progressive document processing.
 * Represents the current state of a document in the research pipeline.
 */
export type DocumentStatus = "fetched" | "analyzing" | "analyzed" | "error"

/**
 * Client-friendly representation of a search query generated by the research agent.
 * Simplified from the full BAML SearchQueryItem type for UI consumption.
 */
export interface ClientSearchQuery {
  query_string: string
  expected_information_summary?: string // Summarized from BAML type
  iterationIndex?: number // Track which iteration this query came from
  timestamp?: string // ISO timestamp when query was generated
}

/**
 * Client-friendly representation of a legal entity extracted from document analysis.
 * Simplified from the full BAML LegalEntity type for UI consumption.
 */
export interface ClientLegalEntity {
  name: string
  type:
    | "Case"
    | "Statute"
    | "Regulation"
    | "Person"
    | "Organization"
    | "LegalConcept"
    | "Jurisdiction"
  details?: string
}

/**
 * Client-friendly representation of analysis reasoning from document processing.
 * Contains summarized versions of the detailed reasoning steps for UI display.
 */
export interface ClientAnalysisReasoning {
  analyzeLegalQuestionSummary: string
  considerRelevantPrinciplesSummary: string
  formulateSearchQueriesSummary?: string
  specifyExpectedInfoSummary?: string
  ensureComprehensiveCoverageSummary?: string
}

/**
 * Client-friendly representation of an analyzed document from the research process.
 * Contains UI-relevant fields extracted from the full BAML AnalyzedDocument type.
 * Supports progressive enhancement from fetched → analyzing → analyzed states.
 */
export interface ClientAnalyzedDoc {
  docId: string // Corresponds to SearchResultItem.id
  title?: string
  url?: string
  status: DocumentStatus // Current processing state of the document

  // Basic metadata available immediately after fetching
  source?: string // Source name from Exa API

  // Analysis data (available after LLM processing)
  relevanceScore?: number
  confidenceScore?: number
  summarySnippet?: string // Potentially streaming, progressively built

  // Extended analysis data for evidence analysis display
  keyArguments?: string[]
  extractedEntities?: ClientLegalEntity[]
  extractedQuotes?: string[]
  fullText?: string
  counterArguments?: string[]

  // Analysis reasoning for modal display
  analysisReasoning?: ClientAnalysisReasoning

  // Error handling
  errorMessage?: string // Available when status is "error"

  // Tracking metadata for accumulative display
  iterationIndex?: number // Track which iteration this analysis came from
  timestamp?: string // ISO timestamp when document was analyzed
}

export interface ClientSynthesisTopic {
  title: string
  synthesisSnippet: string // Potentially streaming
  confidence?: number
  docIds?: string[]
  iterationIndex?: number // Track which iteration this synthesis came from
  timestamp?: string // ISO timestamp when synthesis was created
}

export interface ClientSynthesis {
  topics: ClientSynthesisTopic[]
  unansweredAspects?: string[]
  emergingQuestions?: string[]
  reasoningSummary?: string // Summarized
}

export interface ClientReportSection {
  title: string
  content: string // Potentially streaming
}

/**
 * Client-friendly representation of the final legal research report.
 * Optimized for UI display with support for progressive text streaming.
 */
export interface ClientFinalReport {
  title: string
  executiveSummary: string // Potentially streaming
  sections: ClientReportSection[]
  conclusion: string // Potentially streaming
  limitations?: string[]
  appendixDocIds?: string[]
}

/**
 * Client-friendly representation of research assessment from ASSESSING_RESEARCH stage.
 * Contains agent's analysis of research sufficiency and recommended next steps.
 */
export interface ClientResearchAssessment {
  isSufficient: boolean
  assessmentSummary: string // Potentially streaming
  identifiedGaps?: string[]
  nextAction:
    | "REFINE_QUERIES"
    | "NEW_QUERIES"
    | "DEEPER_ANALYSIS_OF_EXISTING_DOCS"
    | "GENERATE_REPORT"
    | "REQUEST_HUMAN_REVIEW"
  suggestedRefinementQueries?: Array<{
    query_string: string
    expected_information_summary?: string
  }>
  documentIdsForDeeperAnalysis?: string[]
  reasoningSummary?: string // Summarized version for UI display
}

/**
 * Represents the current status of the research process.
 * Contains all information needed for UI status display and progress tracking.
 */
export interface ResearchStatus {
  stage: ResearchStage | null
  isLoading: boolean
  error: string | null
  message?: string // General status message from orchestrator
  currentProcessedDoc?: number
  totalDocsToProcess?: number
  currentStreamingField?: string | null // e.g., "executiveSummary", "sections[0].content"
  isPaused?: boolean // Track if research is manually paused
  canResume?: boolean // Track if research can be resumed
}

/**
 * Auto mode configuration and state for the research process.
 * Controls automatic execution of refinement queries and iterations.
 */
export interface AutoModeState {
  isEnabled: boolean // Whether auto mode is currently enabled
  maxIterations: number // Maximum number of iterations before stopping
  currentIteration: number // Current iteration count
  originalQuestion: string // Original legal question for context
}

// --- Core Jotai Atoms ---

// FR3.1.1: researchStatusAtom
export const researchStatusAtom = atom<ResearchStatus>({
  stage: "IDLE", // Initial stage
  isLoading: false,
  error: null,
  message: "Ready to start research.",
  currentProcessedDoc: 0,
  totalDocsToProcess: 0,
  currentStreamingField: null,
})

// FR3.1.2: researchLogAtom
export const researchLogAtom = atom<string[]>([])

// FR3.1.3: generatedQueriesAtom
export const generatedQueriesAtom = atom<ClientSearchQuery[]>([])

// FR3.1.4: analyzedDocsSummaryAtom
// Using an array for easier UI mapping and ordered display
export const analyzedDocsSummaryAtom = atom<ClientAnalyzedDoc[]>([])

// FR3.1.5: synthesisDetailsAtom
export const synthesisDetailsAtom = atom<ClientSynthesis>({
  topics: [],
  unansweredAspects: [],
  emergingQuestions: [],
  reasoningSummary: "",
})

// FR3.1.6: finalReportContentAtom
export const finalReportContentAtom = atom<ClientFinalReport>({
  title: "",
  executiveSummary: "",
  sections: [],
  conclusion: "",
  limitations: [],
  appendixDocIds: [],
})

// FR3.1.7: researchAssessmentAtom (Phase 4 requirement)
export const researchAssessmentAtom = atom<ClientResearchAssessment | null>(
  null
)

// Auto mode state atom
export const autoModeStateAtom = atom<AutoModeState>({
  isEnabled: false,
  maxIterations: 5, // Default maximum iterations
  currentIteration: 0,
  originalQuestion: "",
})

// Research session state for pause/resume functionality
export const researchSessionAtom = atom<{
  sessionId: string | null
  accumulatedQueries: ClientSearchQuery[]
  accumulatedDocuments: ClientAnalyzedDoc[]
  accumulatedTopics: ClientSynthesisTopic[]
}>({
  sessionId: null,
  accumulatedQueries: [],
  accumulatedDocuments: [],
  accumulatedTopics: [],
})

// --- Derived Atoms (Optional but Recommended for UI Convenience) ---

export const isResearchLoadingAtom = atom(
  get => get(researchStatusAtom).isLoading
)

export const currentResearchStageAtom = atom(
  get => get(researchStatusAtom).stage
)

export const researchErrorAtom = atom(get => get(researchStatusAtom).error)

// Example: Atom for a specific streaming text field for easier consumption
export const executiveSummaryDisplayAtom = atom(
  get => get(finalReportContentAtom).executiveSummary
)

export const reportSectionsDisplayAtom = atom(
  get => get(finalReportContentAtom).sections
)

// Atom for tracking which analyzed document is currently selected in the UI
export const selectedAnalyzedDocIdAtom = atom<string | null>(null)

// --- Reset Functionality ---

/**
 * Write-only Jotai atom that resets all research-related state to initial values.
 *
 * This atom serves as a centralized reset mechanism for the entire research workflow.
 * When any value is written to this atom, it triggers a complete reset of all research
 * atoms including status, logs, generated queries, analyzed documents, synthesis details,
 * and final report content.
 *
 * @param {any} _value - Any value can be written to trigger the reset (value is ignored)
 *
 * @example
 * ```ts
 * const resetResearch = useSetAtom(resetResearchStateAtom);
 *
 * // Reset all research state
 * resetResearch(null);
 * // or
 * resetResearch('anything');
 * ```
 */
export const resetResearchStateAtom = atom(null, (get, set, _value) => {
  set(researchStatusAtom, {
    stage: "IDLE",
    isLoading: false,
    error: null,
    message: "Ready.",
    currentProcessedDoc: 0,
    totalDocsToProcess: 0,
    currentStreamingField: null,
    isPaused: false,
    canResume: false,
  })
  set(researchLogAtom, [])
  set(generatedQueriesAtom, [])
  set(analyzedDocsSummaryAtom, [])
  set(synthesisDetailsAtom, {
    topics: [],
    unansweredAspects: [],
    emergingQuestions: [],
    reasoningSummary: "",
  })
  set(finalReportContentAtom, {
    title: "",
    executiveSummary: "",
    sections: [],
    conclusion: "",
    limitations: [],
    appendixDocIds: [],
  })
  set(selectedAnalyzedDocIdAtom, null)
  set(researchAssessmentAtom, null)

  // Reset auto mode state but preserve isEnabled setting
  const currentAutoMode = get(autoModeStateAtom)
  set(autoModeStateAtom, {
    ...currentAutoMode,
    currentIteration: 0,
    originalQuestion: "",
  })

  // Reset research session
  set(researchSessionAtom, {
    sessionId: null,
    accumulatedQueries: [],
    accumulatedDocuments: [],
    accumulatedTopics: [],
  })
})

/*
 * Decision on Streaming Text Handling (Step 2.4):
 *
 * For v1 implementation, streaming text will be handled using simple string
 * appends to atom fields. The useResearchAgent hook (Phase 3) will update
 * atoms using patterns like:
 *
 * setFinalReportContentAtom(prev => ({
 *   ...prev,
 *   executiveSummary: prev.executiveSummary + chunk
 * }))
 *
 * React's reconciliation will handle UI updates efficiently. Future versions
 * may use more complex structures (arrays of strings/objects) if fine-grained
 * paragraph-level UI control is needed.
 */
