/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  AnalyzedDocument,  DetailedReasoning,  FinalLegalReport,  LegalEntity,  LegalQueryAnalysis,  LegalReportSection,  NextActionType,  OverallSynthesis,  ReasoningStep,  ResearchAssessment,  SearchQueryItem,  SearchResultItem,  SynthesizedTopic } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "AnalyzeSingleDocument" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeSingleDocument"
 * with the specified parameters.
 *
 * @param { SearchResultItem } document - Input parameter.
 * @param { string } original_legal_question - Input parameter.
 *
 * @returns {Promise<AnalyzedDocument>} A promise that resolves with the result of the action.
 */
export const AnalyzeSingleDocument = async (
  document: SearchResultItem,
  original_legal_question: string,
): Promise<AnalyzedDocument> => {
  return b.AnalyzeSingleDocument(
    document,
    original_legal_question,
  );
};

/**
 * Executes the "AssessResearchAndPlanNextSteps" BAML action.
 *
 * This server action calls the underlying BAML function "AssessResearchAndPlanNextSteps"
 * with the specified parameters.
 *
 * @param { string } original_legal_question - Input parameter.
 * @param { LegalQueryAnalysis } initial_queries_analysis - Input parameter.
 * @param { OverallSynthesis | null } current_synthesis (optional) - Input parameter.
 *
 * @returns {Promise<ResearchAssessment>} A promise that resolves with the result of the action.
 */
export const AssessResearchAndPlanNextSteps = async (
  original_legal_question: string,
  initial_queries_analysis: LegalQueryAnalysis,
  current_synthesis?: OverallSynthesis | null,
): Promise<ResearchAssessment> => {
  return b.AssessResearchAndPlanNextSteps(
    original_legal_question,
    initial_queries_analysis,
    current_synthesis,
  );
};

/**
 * Executes the "GenerateFinalLegalReport" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateFinalLegalReport"
 * with the specified parameters.
 *
 * @param { string } original_legal_question - Input parameter.
 * @param { OverallSynthesis } synthesis - Input parameter.
 * @param { LegalQueryAnalysis[] } query_history - Input parameter.
 *
 * @returns {Promise<FinalLegalReport>} A promise that resolves with the result of the action.
 */
export const GenerateFinalLegalReport = async (
  original_legal_question: string,
  synthesis: OverallSynthesis,
  query_history: LegalQueryAnalysis[],
): Promise<FinalLegalReport> => {
  return b.GenerateFinalLegalReport(
    original_legal_question,
    synthesis,
    query_history,
  );
};

/**
 * Executes the "GenerateLegalSearchQueries" BAML action.
 *
 * This server action calls the underlying BAML function "GenerateLegalSearchQueries"
 * with the specified parameters.
 *
 * @param { string } legal_question - Input parameter.
 *
 * @returns {Promise<LegalQueryAnalysis>} A promise that resolves with the result of the action.
 */
export const GenerateLegalSearchQueries = async (
  legal_question: string,
): Promise<LegalQueryAnalysis> => {
  return b.GenerateLegalSearchQueries(
    legal_question,
  );
};

/**
 * Executes the "SynthesizeAllFindings" BAML action.
 *
 * This server action calls the underlying BAML function "SynthesizeAllFindings"
 * with the specified parameters.
 *
 * @param { AnalyzedDocument[] } analyzed_docs - Input parameter.
 * @param { string } original_legal_question - Input parameter.
 *
 * @returns {Promise<OverallSynthesis>} A promise that resolves with the result of the action.
 */
export const SynthesizeAllFindings = async (
  analyzed_docs: AnalyzedDocument[],
  original_legal_question: string,
): Promise<OverallSynthesis> => {
  return b.SynthesizeAllFindings(
    analyzed_docs,
    original_legal_question,
  );
};