/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import type { Audio, Image } from "@boundaryml/baml";
import { b } from "../index";
import type { Check, Checked } from "../types";

import type {
	AnalyzedDocument,
	DetailedReasoning,
	FinalLegalReport,
	LegalEntity,
	LegalQueryAnalysis,
	LegalReportSection,
	NextActionType,
	OverallSynthesis,
	ReasoningStep,
	ResearchAssessment,
	SearchQueryItem,
	SearchResultItem,
	SynthesizedTopic,
} from "../types";

import type * as types from "../types";

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "AnalyzeSingleDocument" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { SearchResultItem } document - Input parameter.
 * @param { string } original_legal_question - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeSingleDocument = async (
	document: SearchResultItem,
	original_legal_question: string,
): Promise<ReadableStream<Uint8Array>> => {
	const stream = b.stream.AnalyzeSingleDocument(
		document,
		original_legal_question,
	);
	return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AssessResearchAndPlanNextSteps" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } original_legal_question - Input parameter.
 * @param { LegalQueryAnalysis } initial_queries_analysis - Input parameter.
 * @param { OverallSynthesis | null } current_synthesis (optional) - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AssessResearchAndPlanNextSteps = async (
	original_legal_question: string,
	initial_queries_analysis: LegalQueryAnalysis,
	current_synthesis?: OverallSynthesis | null,
): Promise<ReadableStream<Uint8Array>> => {
	const stream = b.stream.AssessResearchAndPlanNextSteps(
		original_legal_question,
		initial_queries_analysis,
		current_synthesis,
	);
	return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "GenerateFinalLegalReport" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } original_legal_question - Input parameter.
 * @param { OverallSynthesis } synthesis - Input parameter.
 * @param { LegalQueryAnalysis[] } query_history - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GenerateFinalLegalReport = async (
	original_legal_question: string,
	synthesis: OverallSynthesis,
	query_history: LegalQueryAnalysis[],
): Promise<ReadableStream<Uint8Array>> => {
	const stream = b.stream.GenerateFinalLegalReport(
		original_legal_question,
		synthesis,
		query_history,
	);
	return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "GenerateLegalSearchQueries" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } legal_question - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GenerateLegalSearchQueries = async (
	legal_question: string,
): Promise<ReadableStream<Uint8Array>> => {
	const stream = b.stream.GenerateLegalSearchQueries(legal_question);
	return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "SynthesizeAllFindings" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { AnalyzedDocument[] } analyzed_docs - Input parameter.
 * @param { string } original_legal_question - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const SynthesizeAllFindings = async (
	analyzed_docs: AnalyzedDocument[],
	original_legal_question: string,
): Promise<ReadableStream<Uint8Array>> => {
	const stream = b.stream.SynthesizeAllFindings(
		analyzed_docs,
		original_legal_question,
	);
	return Promise.resolve(stream.toStreamable());
};
