/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

import type { Audio, Image } from "@boundaryml/baml";
// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Check, Checked  } from "../types";

import type {
	AnalyzedDocument,
	DetailedReasoning,
	FinalLegalReport,
	LegalEntity,
	LegalQueryAnalysis,
	LegalReportSection,
	NextActionType,
	OverallSynthesis,
	ReasoningStep,
	ResearchAssessment,
	SearchQueryItem,
	SearchResultItem,
	SynthesizedTopic,
} from "../types";

import type { partial_types } from "../partial_types";
import type * as types from "../types";

export type StreamingServerTypes = {
	AnalyzeSingleDocument: partial_types.AnalyzedDocument;
	AssessResearchAndPlanNextSteps: partial_types.ResearchAssessment;
	GenerateFinalLegalReport: partial_types.FinalLegalReport;
	GenerateLegalSearchQueries: partial_types.LegalQueryAnalysis;
	SynthesizeAllFindings: partial_types.OverallSynthesis;
};
