import axios, { type AxiosResponse } from "axios";
import { config } from "dotenv";

// Load environment variables
config();

// Import BAML types from shared types package
import type {
  SearchResultItem as BamlSearchResultItem,
  SearchQueryItem,
} from "../../packages/shared-types/src/baml-types.js";

// Import validated environment
import { env } from "@/lib/schemas";
// Import error recovery system
import { createSearchContext, SearchCircuitBreaker } from "./errorRecovery";
// Import enhanced error handler
import {
  analyzeExaError,
  executeWithRetry,
  shouldAbortResearch,
} from "./exaErrorHandler";
// Import custom error types
import {
  ExaAuthError,
  ExaClientError,
  ExaConfigError,
  ExaNetworkError,
  ExaParsingError,
  ExaRateLimitError,
  ExaServerError,
} from "./exaSearchErrors";
import { defaultRecoveryStrategies } from "./recoveryStrategies";

// --- Interfaces for Exa API Response (based on OpenAPI spec and examples) ---

interface ExaHighlightOptions {
  num_sentences?: number;
  highlights_per_url?: number;
  query?: string; // A query to focus highlights, different from the main search query
}

interface ExaTextOptions {
  max_characters?: number;
  include_html_tags?: boolean;
}

interface ExaContentsOptions {
  text?: boolean | ExaTextOptions;
  highlights?: boolean | ExaHighlightOptions;
  // summary?: boolean | { query?: string; schema?: any }; // If you plan to use Exa's summary
}

interface ExaSearchRequestBody {
  query: string;
  num_results?: number;
  include_domains?: string[];
  exclude_domains?: string[];
  start_crawl_date?: string; // ISO 8601
  end_crawl_date?: string; // ISO 8601
  start_published_date?: string; // ISO 8601
  end_published_date?: string; // ISO 8601
  type?: "keyword" | "neural" | "auto";
  category?:
    | "company"
    | "research paper"
    | "news"
    | "pdf"
    | "github"
    | "tweet"
    | "personal site"
    | "linkedin profile"
    | "financial report"; // and others
  contents?: ExaContentsOptions;
  // use_autoprompt?: boolean; // This seems to be part of older or specific SDK methods, for API it's often handled by query phrasing
}

interface ExaApiResult {
  id: string; // Exa's internal ID for the document
  url: string;
  title?: string | null;
  author?: string | null;
  score?: number | null;
  publishedDate?: string | null; // Format "YYYY-MM-DD" or full ISO8601 from Exa
  text?: string; // Full text content if requested
  highlights?: string[];
  highlightScores?: number[];
  // Other fields like 'image', 'favicon' might exist
}

interface ExaSearchApiResponse {
  results: ExaApiResult[];
  autopromptString?: string | null; // If Exa modifies the query
  requestId?: string;
  // resolvedSearchType?: 'keyword' | 'neural'; // If type='auto'
}

// --- Configuration ---

const EXA_API_BASE_URL = "https://api.exa.ai";

// Initialize circuit breaker with default recovery strategies
const searchCircuitBreaker = new SearchCircuitBreaker(
  defaultRecoveryStrategies
);

// --- Utility Functions ---

/**
 * Executes a search query using the Exa API and maps the results
 * to the BAML SearchResultItem schema.
 *
 * @param bamlSearchQuery - The SearchQueryItem generated by a BAML function.
 * @param numResults - Number of results to fetch from Exa.
 * @param fetchFullText - Whether to fetch the full text of the results.
 * @param fetchHighlights - Number of highlight sentences to fetch.
 * @returns A promise that resolves to an array of BamlSearchResultItem.
 */
function validateApiKey(): string {
  // Use validated environment instead of direct process.env access
  const EXA_API_KEY = env.EXA_API_KEY;

  if (!EXA_API_KEY || EXA_API_KEY.trim() === "") {
    throw new ExaConfigError("EXA_API_KEY environment variable is not set", {
      configType: "missing_api_key",
    });
  }

  return EXA_API_KEY;
}

function buildRequestBody(
  bamlSearchQuery: SearchQueryItem,
  numResults: number,
  fetchFullText: boolean,
  numHighlightSentences: number
): ExaSearchRequestBody {
  const requestBody: ExaSearchRequestBody = {
    query: bamlSearchQuery.query_string,
    num_results: numResults,
    type: "auto",
    contents: {},
  };

  if (fetchFullText) {
    requestBody.contents = { ...requestBody.contents, text: true };
  }

  if (numHighlightSentences > 0) {
    requestBody.contents = {
      ...requestBody.contents,
      highlights: { num_sentences: numHighlightSentences },
    };
  }

  return requestBody;
}

async function makeExaApiRequest(
  requestBody: ExaSearchRequestBody,
  apiKey: string
): Promise<AxiosResponse<ExaSearchApiResponse>> {
  console.log(`Executing Exa search for: "${requestBody.query}"`);
  console.log("Request body:", JSON.stringify(requestBody, null, 2));

  try {
    console.log("Making axios request to:", `${EXA_API_BASE_URL}/search`);
    console.log("Headers:", {
      "Content-Type": "application/json",
      "x-api-key": `${apiKey.substring(0, 8)}...`,
    });

    const response = await axios.post<ExaSearchApiResponse>(
      `${EXA_API_BASE_URL}/search`,
      requestBody,
      {
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
        },
        timeout: 30000,
        validateStatus: () => true,
      }
    );

    console.log("Axios response received:", {
      status: response?.status,
      statusText: response?.statusText,
      hasData: !!response?.data,
      dataType: typeof response?.data,
    });

    // Handle different HTTP status codes with appropriate Exa error types
    if (response.status >= 400) {
      throw createExaErrorFromResponse(response, requestBody.query);
    }

    return response;
  } catch (requestError) {
    // Handle network/connection errors
    if (axios.isAxiosError(requestError)) {
      if (
        requestError.code === "ECONNABORTED" ||
        requestError.code === "ETIMEDOUT"
      ) {
        throw new ExaNetworkError(
          `Request timeout after 30 seconds for query: "${requestBody.query}"`,
          {
            query: requestBody.query,
            isTimeout: true,
            cause: requestError,
          }
        );
      }

      if (
        requestError.code === "ECONNREFUSED" ||
        requestError.code === "ENOTFOUND"
      ) {
        throw new ExaNetworkError(
          `Connection failed to Exa API for query: "${requestBody.query}"`,
          {
            query: requestBody.query,
            isConnectionError: true,
            cause: requestError,
          }
        );
      }

      // If it's an HTTP error response, handle it
      if (requestError.response) {
        throw createExaErrorFromResponse(
          requestError.response,
          requestBody.query
        );
      }
    }

    console.error("Axios request failed:", {
      message:
        requestError instanceof Error
          ? requestError.message
          : String(requestError),
      code: (requestError as unknown as { code?: string })?.code,
      errno: (requestError as unknown as { errno?: string })?.errno,
      syscall: (requestError as unknown as { syscall?: string })?.syscall,
      stack: requestError instanceof Error ? requestError.stack : undefined,
    });

    // Handle unknown errors appropriately
    if (requestError instanceof Error) {
      // For Error objects, treat as network errors and check for timeout
      const errorMessage = requestError.message;
      const isTimeout = errorMessage.toLowerCase().includes("timeout");

      throw new ExaNetworkError(
        `Unexpected network error for query: "${requestBody.query}"`,
        {
          query: requestBody.query,
          isTimeout,
          cause: requestError,
        }
      );
    }
    // For non-Error objects, treat as parsing errors (unexpected data structure)
    throw new ExaParsingError(
      `Unexpected error during Exa search for query: "${requestBody.query}"`,
      {
        response: requestError,
        expectedFormat: "Error object",
        actualFormat: typeof requestError,
      }
    );
  }
}

/**
 * Creates appropriate Exa error types based on HTTP response status and content
 */
function createExaErrorFromResponse(
  response: AxiosResponse,
  query: string
): Error {
  const status = response.status;
  const data = response.data;
  const message =
    typeof data === "object" && data?.message
      ? data.message
      : `HTTP ${status} error`;

  switch (status) {
    case 401:
      return new ExaAuthError(`Authentication failed: ${message}`, {
        status,
        response: data,
        query,
        authType: message.toLowerCase().includes("invalid")
          ? "invalid_key"
          : "unknown",
      });

    case 403:
      return new ExaAuthError(`Access forbidden: ${message}`, {
        status,
        response: data,
        query,
        authType: "insufficient_permissions",
      });

    case 429: {
      const retryAfterHeader = response.headers["retry-after"];
      const retryAfter = retryAfterHeader
        ? Number.parseInt(retryAfterHeader, 10)
        : undefined;
      const rateLimitType = message.toLowerCase().includes("quota")
        ? "quota"
        : "requests";
      const rateLimitOptions: Record<string, unknown> = {
        status,
        response: data,
        rateLimitType,
      };

      if (typeof query === "string") {
        rateLimitOptions.query = query;
      }

      if (retryAfter !== undefined) {
        rateLimitOptions.retryAfter = retryAfter;
      }

      return new ExaRateLimitError(
        `Rate limit exceeded: ${message}`,
        rateLimitOptions
      );
    }

    case 400:
    case 422:
      return new ExaClientError(`Invalid request: ${message}`, {
        status,
        response: data,
        query,
        errorCode:
          typeof data === "object" && data?.code ? data.code : undefined,
        validationErrors:
          typeof data === "object" && Array.isArray(data?.errors)
            ? data.errors
            : undefined,
      });

    case 408:
      return new ExaClientError(`Request timeout: ${message}`, {
        status,
        response: data,
        query,
        errorCode: "timeout",
      });

    case 500:
    case 502:
    case 503:
    case 504:
      return new ExaServerError(`Server error: ${message}`, {
        status,
        response: data,
        query,
        isTemporary: status === 503 || status === 502 || status === 504,
      });

    default:
      // Unknown HTTP error - treat as server error if 5xx, client error if 4xx
      if (status >= 500) {
        return new ExaServerError(`Unknown server error: ${message}`, {
          status,
          response: data,
          query,
          isTemporary: true,
        });
      }
      if (status >= 400) {
        return new ExaClientError(`Unknown client error: ${message}`, {
          status,
          response: data,
          query,
        });
      }
      return new Error(`Unexpected HTTP status ${status}: ${message}`);
  }
}

function validateApiResponse(
  response: AxiosResponse<ExaSearchApiResponse> | null,
  queryString: string
): ExaApiResult[] {
  if (!response) {
    throw new ExaNetworkError(
      `No response received from Exa API for query "${queryString}"`,
      {
        query: queryString,
        isTimeout: false,
        isConnectionError: true,
        cause: new Error("Response is undefined"),
      }
    );
  }

  if (!response.data || typeof response.data !== "object") {
    throw new ExaParsingError(
      "Invalid response format: Response data is missing or not an object",
      {
        response: response?.data,
        expectedFormat: "object with results array",
        actualFormat: response ? typeof response.data : "undefined response",
      }
    );
  }

  const exaResults = response.data.results;
  if (!Array.isArray(exaResults)) {
    throw new ExaParsingError(
      "Invalid response format: Results field is not an array",
      {
        response: response.data,
        expectedFormat: "array of search results",
        actualFormat: Array.isArray(exaResults) ? "array" : typeof exaResults,
      }
    );
  }

  return exaResults;
}

function validateResultItem(exaRes: ExaApiResult, index: number): void {
  if (!exaRes || typeof exaRes !== "object") {
    throw new ExaParsingError(
      `Invalid result format at index ${index}: Result is not an object`,
      {
        response: exaRes,
        expectedFormat: "search result object",
        actualFormat: typeof exaRes,
      }
    );
  }

  if (!exaRes.url || typeof exaRes.url !== "string") {
    throw new ExaParsingError(
      `Invalid result format at index ${index}: Missing or invalid URL`,
      {
        response: exaRes,
        expectedFormat: "string URL",
        actualFormat: typeof exaRes.url,
      }
    );
  }
}

function mapExaResultToBaml(
  exaRes: ExaApiResult,
  index: number,
  retrievalDate: string,
  bamlSearchQuery: SearchQueryItem,
  autopromptString?: string
): BamlSearchResultItem {
  validateResultItem(exaRes, index);

  let snippet: string | null = null;
  if (exaRes.highlights && exaRes.highlights.length > 0) {
    snippet = exaRes.highlights.slice(0, 2).join(" ... ");
  }

  const metadata: Record<string, string> = {
    exa_internal_id: exaRes.id || "unknown",
  };
  if (autopromptString) {
    metadata.exa_autoprompt = autopromptString;
  }

  return {
    id: exaRes.url,
    url: exaRes.url,
    title: exaRes.title ?? null,
    source_name: "Exa Search",
    snippet: snippet,
    full_text: exaRes.text ?? null,
    published_date: exaRes.publishedDate ?? null,
    retrieval_date: retrievalDate,
    author: exaRes.author ?? null,
    score: exaRes.score ?? null,
    original_query: bamlSearchQuery,
    metadata: metadata,
  };
}

/**
 * Direct search execution with circuit breaker error handling
 * Uses the enhanced error handler for sophisticated retry logic
 */
async function executeExaSearchDirect(
  bamlSearchQuery: SearchQueryItem,
  numResults = 5,
  fetchFullText = true,
  numHighlightSentences = 3
): Promise<BamlSearchResultItem[]> {
  const apiKey = validateApiKey();

  // Use circuit breaker with enhanced error handling
  return await executeWithRetry(
    async () => {
      const requestBody = buildRequestBody(
        bamlSearchQuery,
        numResults,
        fetchFullText,
        numHighlightSentences
      );

      const response = await makeExaApiRequest(requestBody, apiKey);
      const exaResults = validateApiResponse(
        response,
        bamlSearchQuery.query_string
      );
      const retrievalDate = new Date().toISOString();

      const bamlResults: BamlSearchResultItem[] = exaResults.map(
        (exaRes, index) =>
          mapExaResultToBaml(
            exaRes,
            index,
            retrievalDate,
            bamlSearchQuery,
            response.data.autopromptString ?? undefined
          )
      );

      console.log(`Exa search yielded ${bamlResults.length} results.`);
      return bamlResults;
    },
    {
      maxRetries: 3,
      maxDelay: 30000,
      backoffMultiplier: 2,
    }
  );
}

/**
 * Main search function with circuit breaker error recovery
 * Combines enhanced error analysis with recovery strategies
 */
export async function executeExaSearch(
  bamlSearchQuery: SearchQueryItem,
  numResults = 5,
  fetchFullText = true,
  numHighlightSentences = 3
): Promise<BamlSearchResultItem[]> {
  try {
    // Direct execution with built-in circuit breaker retry logic
    return await executeExaSearchDirect(
      bamlSearchQuery,
      numResults,
      fetchFullText,
      numHighlightSentences
    );
  } catch (error) {
    // Analyze error to determine if research should be aborted
    const errorAnalysis = analyzeExaError(error);

    console.warn("Search failed with analysis:", {
      category: errorAnalysis.errorCategory,
      shouldRetry: errorAnalysis.shouldRetry,
      isRecoverable: errorAnalysis.isRecoverable,
      userMessage: errorAnalysis.userMessage,
      shouldAbort: shouldAbortResearch(error),
    });

    // If error is non-recoverable (config/auth), don't try recovery strategies
    if (shouldAbortResearch(error)) {
      console.error(
        "Aborting research due to non-recoverable error:",
        errorAnalysis.userMessage
      );
      throw error;
    }

    // For recoverable errors, try the recovery strategies as fallback
    console.log("Attempting recovery strategies as fallback...");
    const context = createSearchContext([bamlSearchQuery]);

    return await searchCircuitBreaker.executeWithRecovery(
      () =>
        executeExaSearchDirect(
          bamlSearchQuery,
          numResults,
          fetchFullText,
          numHighlightSentences
        ),
      context
    );
  }
}
