import axios, { type AxiosResponse } from "axios";
import { config } from "dotenv";

// Load environment variables
config();

// Assuming BAML-generated types are available.
// You might need to adjust the import path based on your `generators.baml` output_dir.
import type {
  SearchResultItem as BamlSearchResultItem,
  SearchQueryItem,
} from "@/baml_client/types";

// Import validated environment
import { env } from "@/lib/schemas/env";
// Import error recovery system
import { createSearchContext, SearchCircuitBreaker } from "./errorRecovery";
// Import custom error types
import {
  ExaConfigError,
  ExaNetworkError,
  ExaParsingError,
} from "./exaSearchErrors";
import { defaultRecoveryStrategies } from "./recoveryStrategies";

// --- Interfaces for Exa API Response (based on OpenAPI spec and examples) ---

interface ExaHighlightOptions {
  num_sentences?: number;
  highlights_per_url?: number;
  query?: string; // A query to focus highlights, different from the main search query
}

interface ExaTextOptions {
  max_characters?: number;
  include_html_tags?: boolean;
}

interface ExaContentsOptions {
  text?: boolean | ExaTextOptions;
  highlights?: boolean | ExaHighlightOptions;
  // summary?: boolean | { query?: string; schema?: any }; // If you plan to use Exa's summary
}

interface ExaSearchRequestBody {
  query: string;
  num_results?: number;
  include_domains?: string[];
  exclude_domains?: string[];
  start_crawl_date?: string; // ISO 8601
  end_crawl_date?: string; // ISO 8601
  start_published_date?: string; // ISO 8601
  end_published_date?: string; // ISO 8601
  type?: "keyword" | "neural" | "auto";
  category?:
    | "company"
    | "research paper"
    | "news"
    | "pdf"
    | "github"
    | "tweet"
    | "personal site"
    | "linkedin profile"
    | "financial report"; // and others
  contents?: ExaContentsOptions;
  // use_autoprompt?: boolean; // This seems to be part of older or specific SDK methods, for API it's often handled by query phrasing
}

interface ExaApiResult {
  id: string; // Exa's internal ID for the document
  url: string;
  title?: string | null;
  author?: string | null;
  score?: number | null;
  publishedDate?: string | null; // Format "YYYY-MM-DD" or full ISO8601 from Exa
  text?: string; // Full text content if requested
  highlights?: string[];
  highlightScores?: number[];
  // Other fields like 'image', 'favicon' might exist
}

interface ExaSearchApiResponse {
  results: ExaApiResult[];
  autopromptString?: string | null; // If Exa modifies the query
  requestId?: string;
  // resolvedSearchType?: 'keyword' | 'neural'; // If type='auto'
}

// --- Configuration ---

const EXA_API_BASE_URL = "https://api.exa.ai";

// Initialize circuit breaker with default recovery strategies
const searchCircuitBreaker = new SearchCircuitBreaker(
  defaultRecoveryStrategies
);

// --- Utility Functions ---

/**
 * Executes a search query using the Exa API and maps the results
 * to the BAML SearchResultItem schema.
 *
 * @param bamlSearchQuery - The SearchQueryItem generated by a BAML function.
 * @param numResults - Number of results to fetch from Exa.
 * @param fetchFullText - Whether to fetch the full text of the results.
 * @param fetchHighlights - Number of highlight sentences to fetch.
 * @returns A promise that resolves to an array of BamlSearchResultItem.
 */
function validateApiKey(): string {
  // Use validated environment instead of direct process.env access
  const EXA_API_KEY = env.EXA_API_KEY;

  if (!EXA_API_KEY || EXA_API_KEY.trim() === "") {
    throw new ExaConfigError("EXA_API_KEY environment variable is not set", {
      configType: "missing_api_key",
    });
  }

  return EXA_API_KEY;
}

function buildRequestBody(
  bamlSearchQuery: SearchQueryItem,
  numResults: number,
  fetchFullText: boolean,
  numHighlightSentences: number
): ExaSearchRequestBody {
  const requestBody: ExaSearchRequestBody = {
    query: bamlSearchQuery.query_string,
    num_results: numResults,
    type: "auto",
    contents: {},
  };

  if (fetchFullText) {
    requestBody.contents = { ...requestBody.contents, text: true };
  }

  if (numHighlightSentences > 0) {
    requestBody.contents = {
      ...requestBody.contents,
      highlights: { num_sentences: numHighlightSentences },
    };
  }

  return requestBody;
}

async function makeExaApiRequest(
  requestBody: ExaSearchRequestBody,
  apiKey: string
): Promise<AxiosResponse<ExaSearchApiResponse>> {
  console.log(`Executing Exa search for: "${requestBody.query}"`);
  console.log("Request body:", JSON.stringify(requestBody, null, 2));

  try {
    console.log("Making axios request to:", `${EXA_API_BASE_URL}/search`);
    console.log("Headers:", {
      "Content-Type": "application/json",
      "x-api-key": `${apiKey.substring(0, 8)}...`,
    });

    const response = await axios.post<ExaSearchApiResponse>(
      `${EXA_API_BASE_URL}/search`,
      requestBody,
      {
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
        },
        timeout: 30000,
        validateStatus: () => true,
      }
    );

    console.log("Axios response received:", {
      status: response?.status,
      statusText: response?.statusText,
      hasData: !!response?.data,
      dataType: typeof response?.data,
    });

    return response;
  } catch (requestError) {
    console.error("Axios request failed:", {
      message:
        requestError instanceof Error
          ? requestError.message
          : String(requestError),
      code: (requestError as unknown as { code?: string })?.code,
      errno: (requestError as unknown as { errno?: string })?.errno,
      syscall: (requestError as unknown as { syscall?: string })?.syscall,
      stack: requestError instanceof Error ? requestError.stack : undefined,
    });
    throw requestError;
  }
}

function validateApiResponse(
  response: AxiosResponse<ExaSearchApiResponse> | null,
  queryString: string
): ExaApiResult[] {
  if (!response) {
    throw new ExaNetworkError(
      `No response received from Exa API for query "${queryString}"`,
      {
        query: queryString,
        isTimeout: false,
        isConnectionError: true,
        cause: new Error("Response is undefined"),
      }
    );
  }

  if (!response.data || typeof response.data !== "object") {
    throw new ExaParsingError(
      "Invalid response format: Response data is missing or not an object",
      {
        response: response?.data,
        expectedFormat: "object with results array",
        actualFormat: response ? typeof response.data : "undefined response",
      }
    );
  }

  const exaResults = response.data.results;
  if (!Array.isArray(exaResults)) {
    throw new ExaParsingError(
      "Invalid response format: Results field is not an array",
      {
        response: response.data,
        expectedFormat: "array of search results",
        actualFormat: Array.isArray(exaResults) ? "array" : typeof exaResults,
      }
    );
  }

  return exaResults;
}

function validateResultItem(exaRes: ExaApiResult, index: number): void {
  if (!exaRes || typeof exaRes !== "object") {
    throw new ExaParsingError(
      `Invalid result format at index ${index}: Result is not an object`,
      {
        response: exaRes,
        expectedFormat: "search result object",
        actualFormat: typeof exaRes,
      }
    );
  }

  if (!exaRes.url || typeof exaRes.url !== "string") {
    throw new ExaParsingError(
      `Invalid result format at index ${index}: Missing or invalid URL`,
      {
        response: exaRes,
        expectedFormat: "string URL",
        actualFormat: typeof exaRes.url,
      }
    );
  }
}

function mapExaResultToBaml(
  exaRes: ExaApiResult,
  index: number,
  retrievalDate: string,
  bamlSearchQuery: SearchQueryItem,
  autopromptString?: string
): BamlSearchResultItem {
  validateResultItem(exaRes, index);

  let snippet: string | null = null;
  if (exaRes.highlights && exaRes.highlights.length > 0) {
    snippet = exaRes.highlights.slice(0, 2).join(" ... ");
  }

  const metadata: Record<string, string> = {
    exa_internal_id: exaRes.id || "unknown",
  };
  if (autopromptString) {
    metadata.exa_autoprompt = autopromptString;
  }

  return {
    id: exaRes.url,
    url: exaRes.url,
    title: exaRes.title ?? null,
    source_name: "Exa Search",
    snippet: snippet,
    full_text: exaRes.text ?? null,
    published_date: exaRes.publishedDate ?? null,
    retrieval_date: retrievalDate,
    author: exaRes.author ?? null,
    score: exaRes.score ?? null,
    original_query: bamlSearchQuery,
    metadata: metadata,
  };
}

/**
 * Direct search execution without circuit breaker recovery
 * Used internally by recovery strategies for retries
 */
async function executeExaSearchDirect(
  bamlSearchQuery: SearchQueryItem,
  numResults = 5,
  fetchFullText = true,
  numHighlightSentences = 3
): Promise<BamlSearchResultItem[]> {
  const apiKey = validateApiKey();
  const requestBody = buildRequestBody(
    bamlSearchQuery,
    numResults,
    fetchFullText,
    numHighlightSentences
  );

  const response = await makeExaApiRequest(requestBody, apiKey);
  const exaResults = validateApiResponse(
    response,
    bamlSearchQuery.query_string
  );
  const retrievalDate = new Date().toISOString();

  const bamlResults: BamlSearchResultItem[] = exaResults.map((exaRes, index) =>
    mapExaResultToBaml(
      exaRes,
      index,
      retrievalDate,
      bamlSearchQuery,
      response.data.autopromptString ?? undefined
    )
  );

  console.log(`Exa search yielded ${bamlResults.length} results.`);
  return bamlResults;
}

/**
 * Main search function with circuit breaker error recovery
 * This replaces the original implementation with sophisticated error handling
 */
export async function executeExaSearch(
  bamlSearchQuery: SearchQueryItem,
  numResults = 5,
  fetchFullText = true,
  numHighlightSentences = 3
): Promise<BamlSearchResultItem[]> {
  // Create search context for error recovery
  const context = createSearchContext([bamlSearchQuery]);

  // Use circuit breaker to execute search with automatic error recovery
  return await searchCircuitBreaker.executeWithRecovery(
    () =>
      executeExaSearchDirect(
        bamlSearchQuery,
        numResults,
        fetchFullText,
        numHighlightSentences
      ),
    context
  );
}
