/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, FunctionResult, BamlCtxManager, ClientRegistry, Image, Audio, Collector } from "@boundaryml/baml"
import { toBamlError, BamlStream, type HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {AnalyzedDocument, DetailedReasoning, FinalLegalReport, LegalEntity, LegalQueryAnalysis, LegalReportSection, NextActionType, OverallSynthesis, ReasoningStep, ResearchAssessment, SearchQueryItem, SearchResultItem, SynthesizedTopic} from "./types"
import type TypeBuilder from "./type_builder"
import { AsyncHttpRequest, AsyncHttpStreamRequest } from "./async_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

type BamlCallOptions = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  collector?: Collector | Collector[]
  env?: Record<string, string | undefined>
}

export class BamlAsyncClient {
  private runtime: BamlRuntime
  private ctxManager: BamlCtxManager
  private streamClient: BamlStreamClient
  private httpRequest: AsyncHttpRequest
  private httpStreamRequest: AsyncHttpStreamRequest
  private llmResponseParser: LlmResponseParser
  private llmStreamParser: LlmStreamParser
  private bamlOptions: BamlCallOptions

  constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
    this.runtime = runtime
    this.ctxManager = ctxManager
    this.streamClient = new BamlStreamClient(runtime, ctxManager, bamlOptions)
    this.httpRequest = new AsyncHttpRequest(runtime, ctxManager)
    this.httpStreamRequest = new AsyncHttpStreamRequest(runtime, ctxManager)
    this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
    this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
    this.bamlOptions = bamlOptions || {}
  }

  withOptions(bamlOptions: BamlCallOptions) {
    return new BamlAsyncClient(this.runtime, this.ctxManager, bamlOptions)
  }

  get stream() {
    return this.streamClient
  }

  get request() {
    return this.httpRequest
  }

  get streamRequest() {
    return this.httpStreamRequest
  }

  get parse() {
    return this.llmResponseParser
  }

  get parseStream() {
    return this.llmStreamParser
  }

  
  async AnalyzeSingleDocument(
      document: SearchResultItem,original_legal_question: string,
      __baml_options__?: BamlCallOptions
  ): Promise<AnalyzedDocument> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = await this.runtime.callFunction(
        "AnalyzeSingleDocument",
        {
          "document": document,"original_legal_question": original_legal_question
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return raw.parsed(false) as AnalyzedDocument
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  async AssessResearchAndPlanNextSteps(
      original_legal_question: string,initial_queries_analysis: LegalQueryAnalysis,current_synthesis?: OverallSynthesis | null,
      __baml_options__?: BamlCallOptions
  ): Promise<ResearchAssessment> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = await this.runtime.callFunction(
        "AssessResearchAndPlanNextSteps",
        {
          "original_legal_question": original_legal_question,"initial_queries_analysis": initial_queries_analysis,"current_synthesis": current_synthesis?? null
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return raw.parsed(false) as ResearchAssessment
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  async GenerateFinalLegalReport(
      original_legal_question: string,synthesis: OverallSynthesis,query_history: LegalQueryAnalysis[],
      __baml_options__?: BamlCallOptions
  ): Promise<FinalLegalReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = await this.runtime.callFunction(
        "GenerateFinalLegalReport",
        {
          "original_legal_question": original_legal_question,"synthesis": synthesis,"query_history": query_history
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return raw.parsed(false) as FinalLegalReport
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  async GenerateLegalSearchQueries(
      legal_question: string,
      __baml_options__?: BamlCallOptions
  ): Promise<LegalQueryAnalysis> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = await this.runtime.callFunction(
        "GenerateLegalSearchQueries",
        {
          "legal_question": legal_question
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return raw.parsed(false) as LegalQueryAnalysis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  async SynthesizeAllFindings(
      analyzed_docs: AnalyzedDocument[],original_legal_question: string,
      __baml_options__?: BamlCallOptions
  ): Promise<OverallSynthesis> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = await this.runtime.callFunction(
        "SynthesizeAllFindings",
        {
          "analyzed_docs": analyzed_docs,"original_legal_question": original_legal_question
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return raw.parsed(false) as OverallSynthesis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

class BamlStreamClient {
  private runtime: BamlRuntime
  private ctxManager: BamlCtxManager
  private bamlOptions: BamlCallOptions

  constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
    this.runtime = runtime
    this.ctxManager = ctxManager
    this.bamlOptions = bamlOptions || { env: { ...process.env } }
  }

  
  AnalyzeSingleDocument(
      document: SearchResultItem,original_legal_question: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, collector?: Collector | Collector[], env?: Record<string, string | undefined> }
  ): BamlStream<partial_types.AnalyzedDocument, AnalyzedDocument> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = this.runtime.streamFunction(
        "AnalyzeSingleDocument",
        {
          "document": document,"original_legal_question": original_legal_question
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return new BamlStream<partial_types.AnalyzedDocument, AnalyzedDocument>(
        raw,
        (a): partial_types.AnalyzedDocument => a,
        (a): AnalyzedDocument => a,
        this.ctxManager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AssessResearchAndPlanNextSteps(
      original_legal_question: string,initial_queries_analysis: LegalQueryAnalysis,current_synthesis?: OverallSynthesis | null,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, collector?: Collector | Collector[], env?: Record<string, string | undefined> }
  ): BamlStream<partial_types.ResearchAssessment, ResearchAssessment> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = this.runtime.streamFunction(
        "AssessResearchAndPlanNextSteps",
        {
          "original_legal_question": original_legal_question,"initial_queries_analysis": initial_queries_analysis,"current_synthesis": current_synthesis ?? null
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return new BamlStream<partial_types.ResearchAssessment, ResearchAssessment>(
        raw,
        (a): partial_types.ResearchAssessment => a,
        (a): ResearchAssessment => a,
        this.ctxManager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateFinalLegalReport(
      original_legal_question: string,synthesis: OverallSynthesis,query_history: LegalQueryAnalysis[],
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, collector?: Collector | Collector[], env?: Record<string, string | undefined> }
  ): BamlStream<partial_types.FinalLegalReport, FinalLegalReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = this.runtime.streamFunction(
        "GenerateFinalLegalReport",
        {
          "original_legal_question": original_legal_question,"synthesis": synthesis,"query_history": query_history
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return new BamlStream<partial_types.FinalLegalReport, FinalLegalReport>(
        raw,
        (a): partial_types.FinalLegalReport => a,
        (a): FinalLegalReport => a,
        this.ctxManager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateLegalSearchQueries(
      legal_question: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, collector?: Collector | Collector[], env?: Record<string, string | undefined> }
  ): BamlStream<partial_types.LegalQueryAnalysis, LegalQueryAnalysis> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = this.runtime.streamFunction(
        "GenerateLegalSearchQueries",
        {
          "legal_question": legal_question
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return new BamlStream<partial_types.LegalQueryAnalysis, LegalQueryAnalysis>(
        raw,
        (a): partial_types.LegalQueryAnalysis => a,
        (a): LegalQueryAnalysis => a,
        this.ctxManager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SynthesizeAllFindings(
      analyzed_docs: AnalyzedDocument[],original_legal_question: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, collector?: Collector | Collector[], env?: Record<string, string | undefined> }
  ): BamlStream<partial_types.OverallSynthesis, OverallSynthesis> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const collector = options.collector ? (Array.isArray(options.collector) ? options.collector : [options.collector]) : [];
      const env = options.env ? { ...process.env, ...options.env } : { ...process.env };
      const raw = this.runtime.streamFunction(
        "SynthesizeAllFindings",
        {
          "analyzed_docs": analyzed_docs,"original_legal_question": original_legal_question
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
        env,
      )
      return new BamlStream<partial_types.OverallSynthesis, OverallSynthesis>(
        raw,
        (a): partial_types.OverallSynthesis => a,
        (a): OverallSynthesis => a,
        this.ctxManager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)