/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {AnalyzedDocument, DetailedReasoning, FinalLegalReport, LegalEntity, LegalQueryAnalysis, LegalReportSection, NextActionType, OverallSynthesis, ReasoningStep, ResearchAssessment, SearchQueryItem, SearchResultItem, SynthesizedTopic} from "./types"
import type TypeBuilder from "./type_builder"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeSingleDocument(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): AnalyzedDocument {
    try {
      return this.runtime.parseLlmResponse(
        "AnalyzeSingleDocument",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as AnalyzedDocument
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AssessResearchAndPlanNextSteps(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): ResearchAssessment {
    try {
      return this.runtime.parseLlmResponse(
        "AssessResearchAndPlanNextSteps",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as ResearchAssessment
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateFinalLegalReport(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): FinalLegalReport {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateFinalLegalReport",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as FinalLegalReport
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateLegalSearchQueries(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): LegalQueryAnalysis {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateLegalSearchQueries",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as LegalQueryAnalysis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SynthesizeAllFindings(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): OverallSynthesis {
    try {
      return this.runtime.parseLlmResponse(
        "SynthesizeAllFindings",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as OverallSynthesis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeSingleDocument(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.AnalyzedDocument {
    try {
      return this.runtime.parseLlmResponse(
        "AnalyzeSingleDocument",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.AnalyzedDocument
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AssessResearchAndPlanNextSteps(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.ResearchAssessment {
    try {
      return this.runtime.parseLlmResponse(
        "AssessResearchAndPlanNextSteps",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.ResearchAssessment
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateFinalLegalReport(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.FinalLegalReport {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateFinalLegalReport",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.FinalLegalReport
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateLegalSearchQueries(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.LegalQueryAnalysis {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateLegalSearchQueries",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.LegalQueryAnalysis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SynthesizeAllFindings(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.OverallSynthesis {
    try {
      return this.runtime.parseLlmResponse(
        "SynthesizeAllFindings",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.OverallSynthesis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}