/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AnalyzedDocument,  DetailedReasoning,  FinalLegalReport,  LegalEntity,  LegalQueryAnalysis,  LegalReportSection,  NextActionType,  OverallSynthesis,  ReasoningStep,  ResearchAssessment,  SearchQueryItem,  SearchResultItem,  SynthesizedTopic } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface AnalyzedDocument {
        search_result_id?: (string | null)
        relevance_score?: (number | null)
        confidence_score?: (number | null)
        summary?: StreamState<(string | null)>
        key_arguments_and_reasoning?: StreamState<(string | null)[]>
        extracted_entities?: (partial_types.LegalEntity | null)[]
        extracted_quotes?: (string | null)[]
        counter_arguments_or_nuances: ((string | null)[] | null)
        reasoning?: (partial_types.DetailedReasoning | null)
    }
    
    export interface DetailedReasoning {
        analyze_legal_question: partial_types.ReasoningStep
        consider_relevant_legal_principles: partial_types.ReasoningStep
        formulate_search_queries_strategy: partial_types.ReasoningStep
        specify_expected_information_strategy: partial_types.ReasoningStep
        ensure_comprehensive_coverage_strategy: partial_types.ReasoningStep
    }
    
    export interface FinalLegalReport {
        report_title?: (string | null)
        executive_summary?: StreamState<(string | null)>
        sections?: (partial_types.LegalReportSection | null)[]
        conclusion?: StreamState<(string | null)>
        limitations_and_caveats: ((string | null)[] | null)
        appendix_document_ids: ((string | null)[] | null)
    }
    
    export interface LegalEntity {
        name?: (string | null)
        type?: ("Case" | "Statute" | "Regulation" | "Person" | "Organization" | "LegalConcept" | "Jurisdiction" | null)
        details: ((string | null) | null)
    }
    
    export interface LegalQueryAnalysis {
        reasoning?: (partial_types.DetailedReasoning | null)
        search_queries?: (types.SearchQueryItem | null)[]
    }
    
    export interface LegalReportSection {
        section_title?: (string | null)
        content?: StreamState<(string | null)>
    }
    
    export interface OverallSynthesis {
        key_synthesized_topics?: (partial_types.SynthesizedTopic | null)[]
        unanswered_aspects: ((string | null)[] | null)
        emerging_questions: ((string | null)[] | null)
        reasoning?: (partial_types.DetailedReasoning | null)
    }
    
    export interface ReasoningStep {
        summary?: StreamState<(string | null)>
        items_considered: ((string | null)[] | null)
    }
    
    export interface ResearchAssessment {
        is_sufficient?: (boolean | null)
        assessment_summary?: StreamState<(string | null)>
        identified_gaps: ((string | null)[] | null)
        next_action?: (NextActionType | null)
        suggested_queries_for_refinement: ((types.SearchQueryItem | null)[] | null)
        document_ids_for_deeper_analysis: ((string | null)[] | null)
        reasoning?: (partial_types.DetailedReasoning | null)
    }
    
    export interface SearchQueryItem {
        query_string?: (string | null)
        expected_information?: (string | null)[]
    }
    
    export interface SearchResultItem {
        id?: (string | null)
        url?: (string | null)
        title: ((string | null) | null)
        source_name?: (string | null)
        snippet: ((string | null) | null)
        full_text: ((string | null) | null)
        published_date: ((string | null) | null)
        retrieval_date?: (string | null)
        author: ((string | null) | null)
        score: ((number | null) | null)
        original_query: ((types.SearchQueryItem | null) | null)
        metadata: ((Record<string, (string | null)> | null) | null)
    }
    
    export interface SynthesizedTopic {
        topic_title?: (string | null)
        synthesis?: StreamState<(string | null)>
        supporting_document_ids?: (string | null)[]
        confidence_score?: (number | null)
    }
    
}