/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AnalyzedDocument,  DetailedReasoning,  FinalLegalReport,  LegalEntity,  LegalQueryAnalysis,  LegalReportSection,  NextActionType,  OverallSynthesis,  ReasoningStep,  ResearchAssessment,  SearchQueryItem,  SearchResultItem,  SynthesizedTopic } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AnalyzedDocument {
      search_result_id?: string | null
      relevance_score?: number | null
      confidence_score?: number | null
      summary?: StreamState<string | null>
      key_arguments_and_reasoning: string[]
      extracted_entities: LegalEntity[]
      extracted_quotes: string[]
      counter_arguments_or_nuances?: string[] | null
      reasoning?: DetailedReasoning | null
    }
    export interface DetailedReasoning {
      analyze_legal_question: ReasoningStep
      consider_relevant_legal_principles: ReasoningStep
      formulate_search_queries_strategy: ReasoningStep
      specify_expected_information_strategy: ReasoningStep
      ensure_comprehensive_coverage_strategy: ReasoningStep
    }
    export interface FinalLegalReport {
      report_title?: string | null
      executive_summary?: StreamState<string | null>
      sections: LegalReportSection[]
      conclusion?: StreamState<string | null>
      limitations_and_caveats?: string[] | null
      appendix_document_ids?: string[] | null
    }
    export interface LegalEntity {
      name?: string | null
      type?: "Case" | "Statute" | "Regulation" | "Person" | "Organization" | "LegalConcept" | "Jurisdiction" | null
      details?: string | null
    }
    export interface LegalQueryAnalysis {
      reasoning?: DetailedReasoning | null
      search_queries: types.SearchQueryItem[]
    }
    export interface LegalReportSection {
      section_title?: string | null
      content?: StreamState<string | null>
    }
    export interface OverallSynthesis {
      key_synthesized_topics: SynthesizedTopic[]
      unanswered_aspects?: string[] | null
      emerging_questions?: string[] | null
      reasoning?: DetailedReasoning | null
    }
    export interface ReasoningStep {
      summary?: StreamState<string | null>
      items_considered?: string[] | null
    }
    export interface ResearchAssessment {
      is_sufficient?: boolean | null
      assessment_summary?: StreamState<string | null>
      identified_gaps?: string[] | null
      next_action?: types.NextActionType | null
      suggested_queries_for_refinement?: types.SearchQueryItem[] | null
      document_ids_for_deeper_analysis?: string[] | null
      reasoning?: DetailedReasoning | null
    }
    export interface SearchQueryItem {
      query_string?: string | null
      expected_information: string[]
    }
    export interface SearchResultItem {
      id?: string | null
      url?: string | null
      title?: string | null
      source_name?: string | null
      snippet?: string | null
      full_text?: string | null
      published_date?: string | null
      retrieval_date?: string | null
      author?: string | null
      score?: number | null
      original_query?: types.SearchQueryItem | null
      metadata?: Record<string, string> | null
    }
    export interface SynthesizedTopic {
      topic_title?: string | null
      synthesis?: StreamState<string | null>
      supporting_document_ids: string[]
      confidence_score?: number | null
    }
}