/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio } from "@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {AnalyzedDocument, DetailedReasoning, FinalLegalReport, LegalEntity, LegalQueryAnalysis, LegalReportSection, NextActionType, OverallSynthesis, ReasoningStep, ResearchAssessment, SearchQueryItem, SearchResultItem, SynthesizedTopic} from "./types"
import type TypeBuilder from "./type_builder"

type BamlCallOptions = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeSingleDocument(
      document: SearchResultItem,original_legal_question: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "AnalyzeSingleDocument",
        {
          "document": document,"original_legal_question": original_legal_question
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AssessResearchAndPlanNextSteps(
      original_legal_question: string,initial_queries_analysis: LegalQueryAnalysis,current_synthesis?: OverallSynthesis | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "AssessResearchAndPlanNextSteps",
        {
          "original_legal_question": original_legal_question,"initial_queries_analysis": initial_queries_analysis,"current_synthesis": current_synthesis?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateFinalLegalReport(
      original_legal_question: string,synthesis: OverallSynthesis,query_history: LegalQueryAnalysis[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "GenerateFinalLegalReport",
        {
          "original_legal_question": original_legal_question,"synthesis": synthesis,"query_history": query_history
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateLegalSearchQueries(
      legal_question: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "GenerateLegalSearchQueries",
        {
          "legal_question": legal_question
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SynthesizeAllFindings(
      analyzed_docs: AnalyzedDocument[],original_legal_question: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "SynthesizeAllFindings",
        {
          "analyzed_docs": analyzed_docs,"original_legal_question": original_legal_question
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeSingleDocument(
      document: SearchResultItem,original_legal_question: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "AnalyzeSingleDocument",
        {
          "document": document,"original_legal_question": original_legal_question
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AssessResearchAndPlanNextSteps(
      original_legal_question: string,initial_queries_analysis: LegalQueryAnalysis,current_synthesis?: OverallSynthesis | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "AssessResearchAndPlanNextSteps",
        {
          "original_legal_question": original_legal_question,"initial_queries_analysis": initial_queries_analysis,"current_synthesis": current_synthesis?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateFinalLegalReport(
      original_legal_question: string,synthesis: OverallSynthesis,query_history: LegalQueryAnalysis[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "GenerateFinalLegalReport",
        {
          "original_legal_question": original_legal_question,"synthesis": synthesis,"query_history": query_history
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateLegalSearchQueries(
      legal_question: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "GenerateLegalSearchQueries",
        {
          "legal_question": legal_question
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SynthesizeAllFindings(
      analyzed_docs: AnalyzedDocument[],original_legal_question: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "SynthesizeAllFindings",
        {
          "analyzed_docs": analyzed_docs,"original_legal_question": original_legal_question
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}