/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { FieldType } from '@boundaryml/baml/native'
import {
	type ClassBuilder,
	type ClassViewer,
	type EnumBuilder,
	type EnumViewer,
	TypeBuilder as _TypeBuilder,
} from "@boundaryml/baml/type_builder";
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals";

export default class TypeBuilder {
	private tb: _TypeBuilder;

	AnalyzedDocument: ClassViewer<
		"AnalyzedDocument",
		| "search_result_id"
		| "relevance_score"
		| "confidence_score"
		| "summary"
		| "key_arguments_and_reasoning"
		| "extracted_entities"
		| "extracted_quotes"
		| "counter_arguments_or_nuances"
		| "reasoning"
	>;

	DetailedReasoning: ClassViewer<
		"DetailedReasoning",
		| "analyze_legal_question"
		| "consider_relevant_legal_principles"
		| "formulate_search_queries_strategy"
		| "specify_expected_information_strategy"
		| "ensure_comprehensive_coverage_strategy"
	>;

	FinalLegalReport: ClassViewer<
		"FinalLegalReport",
		| "report_title"
		| "executive_summary"
		| "sections"
		| "conclusion"
		| "limitations_and_caveats"
		| "appendix_document_ids"
	>;

	LegalEntity: ClassViewer<"LegalEntity", "name" | "type" | "details">;

	LegalQueryAnalysis: ClassViewer<
		"LegalQueryAnalysis",
		"reasoning" | "search_queries"
	>;

	LegalReportSection: ClassViewer<
		"LegalReportSection",
		"section_title" | "content"
	>;

	OverallSynthesis: ClassViewer<
		"OverallSynthesis",
		| "key_synthesized_topics"
		| "unanswered_aspects"
		| "emerging_questions"
		| "reasoning"
	>;

	ReasoningStep: ClassViewer<"ReasoningStep", "summary" | "items_considered">;

	ResearchAssessment: ClassViewer<
		"ResearchAssessment",
		| "is_sufficient"
		| "assessment_summary"
		| "identified_gaps"
		| "next_action"
		| "suggested_queries_for_refinement"
		| "document_ids_for_deeper_analysis"
		| "reasoning"
	>;

	SearchQueryItem: ClassViewer<
		"SearchQueryItem",
		"query_string" | "expected_information"
	>;

	SearchResultItem: ClassViewer<
		"SearchResultItem",
		| "id"
		| "url"
		| "title"
		| "source_name"
		| "snippet"
		| "full_text"
		| "published_date"
		| "retrieval_date"
		| "author"
		| "score"
		| "original_query"
		| "metadata"
	>;

	SynthesizedTopic: ClassViewer<
		"SynthesizedTopic",
		"topic_title" | "synthesis" | "supporting_document_ids" | "confidence_score"
	>;

	NextActionType: EnumViewer<
		"NextActionType",
		| "REFINE_QUERIES"
		| "NEW_QUERIES"
		| "DEEPER_ANALYSIS_OF_EXISTING_DOCS"
		| "GENERATE_REPORT"
		| "REQUEST_HUMAN_REVIEW"
	>;

	constructor() {
		this.tb = new _TypeBuilder({
			classes: new Set([
				"AnalyzedDocument",
				"DetailedReasoning",
				"FinalLegalReport",
				"LegalEntity",
				"LegalQueryAnalysis",
				"LegalReportSection",
				"OverallSynthesis",
				"ReasoningStep",
				"ResearchAssessment",
				"SearchQueryItem",
				"SearchResultItem",
				"SynthesizedTopic",
			]),
			enums: new Set(["NextActionType"]),
			runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
		});

		this.AnalyzedDocument = this.tb.classViewer("AnalyzedDocument", [
			"search_result_id",
			"relevance_score",
			"confidence_score",
			"summary",
			"key_arguments_and_reasoning",
			"extracted_entities",
			"extracted_quotes",
			"counter_arguments_or_nuances",
			"reasoning",
		]);

		this.DetailedReasoning = this.tb.classViewer("DetailedReasoning", [
			"analyze_legal_question",
			"consider_relevant_legal_principles",
			"formulate_search_queries_strategy",
			"specify_expected_information_strategy",
			"ensure_comprehensive_coverage_strategy",
		]);

		this.FinalLegalReport = this.tb.classViewer("FinalLegalReport", [
			"report_title",
			"executive_summary",
			"sections",
			"conclusion",
			"limitations_and_caveats",
			"appendix_document_ids",
		]);

		this.LegalEntity = this.tb.classViewer("LegalEntity", [
			"name",
			"type",
			"details",
		]);

		this.LegalQueryAnalysis = this.tb.classViewer("LegalQueryAnalysis", [
			"reasoning",
			"search_queries",
		]);

		this.LegalReportSection = this.tb.classViewer("LegalReportSection", [
			"section_title",
			"content",
		]);

		this.OverallSynthesis = this.tb.classViewer("OverallSynthesis", [
			"key_synthesized_topics",
			"unanswered_aspects",
			"emerging_questions",
			"reasoning",
		]);

		this.ReasoningStep = this.tb.classViewer("ReasoningStep", [
			"summary",
			"items_considered",
		]);

		this.ResearchAssessment = this.tb.classViewer("ResearchAssessment", [
			"is_sufficient",
			"assessment_summary",
			"identified_gaps",
			"next_action",
			"suggested_queries_for_refinement",
			"document_ids_for_deeper_analysis",
			"reasoning",
		]);

		this.SearchQueryItem = this.tb.classViewer("SearchQueryItem", [
			"query_string",
			"expected_information",
		]);

		this.SearchResultItem = this.tb.classViewer("SearchResultItem", [
			"id",
			"url",
			"title",
			"source_name",
			"snippet",
			"full_text",
			"published_date",
			"retrieval_date",
			"author",
			"score",
			"original_query",
			"metadata",
		]);

		this.SynthesizedTopic = this.tb.classViewer("SynthesizedTopic", [
			"topic_title",
			"synthesis",
			"supporting_document_ids",
			"confidence_score",
		]);

		this.NextActionType = this.tb.enumViewer("NextActionType", [
			"REFINE_QUERIES",
			"NEW_QUERIES",
			"DEEPER_ANALYSIS_OF_EXISTING_DOCS",
			"GENERATE_REPORT",
			"REQUEST_HUMAN_REVIEW",
		]);
	}

	__tb() {
		return this.tb._tb();
	}

	string(): FieldType {
		return this.tb.string();
	}

	literalString(value: string): FieldType {
		return this.tb.literalString(value);
	}

	literalInt(value: number): FieldType {
		return this.tb.literalInt(value);
	}

	literalBool(value: boolean): FieldType {
		return this.tb.literalBool(value);
	}

	int(): FieldType {
		return this.tb.int();
	}

	float(): FieldType {
		return this.tb.float();
	}

	bool(): FieldType {
		return this.tb.bool();
	}

	list(type: FieldType): FieldType {
		return this.tb.list(type);
	}

	null(): FieldType {
		return this.tb.null();
	}

	map(key: FieldType, value: FieldType): FieldType {
		return this.tb.map(key, value);
	}

	union(types: FieldType[]): FieldType {
		return this.tb.union(types);
	}

	addClass<Name extends string>(name: Name): ClassBuilder<Name> {
		return this.tb.addClass(name);
	}

	addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
		return this.tb.addEnum(name);
	}

	addBaml(baml: string): void {
		this.tb.addBaml(baml);
	}
}
