/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum NextActionType {
  REFINE_QUERIES = "REFINE_QUERIES",
  NEW_QUERIES = "NEW_QUERIES",
  DEEPER_ANALYSIS_OF_EXISTING_DOCS = "DEEPER_ANALYSIS_OF_EXISTING_DOCS",
  GENERATE_REPORT = "GENERATE_REPORT",
  REQUEST_HUMAN_REVIEW = "REQUEST_HUMAN_REVIEW",
}

export interface AnalyzedDocument {
  search_result_id: string
  relevance_score: number
  confidence_score: number
  summary: string
  key_arguments_and_reasoning: string[]
  extracted_entities: LegalEntity[]
  extracted_quotes: string[]
  counter_arguments_or_nuances?: string[] | null
  reasoning: DetailedReasoning
  
}

export interface DetailedReasoning {
  analyze_legal_question: ReasoningStep
  consider_relevant_legal_principles: ReasoningStep
  formulate_search_queries_strategy: ReasoningStep
  specify_expected_information_strategy: ReasoningStep
  ensure_comprehensive_coverage_strategy: ReasoningStep
  
}

export interface FinalLegalReport {
  report_title: string
  executive_summary: string
  sections: LegalReportSection[]
  conclusion: string
  limitations_and_caveats?: string[] | null
  appendix_document_ids?: string[] | null
  
}

export interface LegalEntity {
  name: string
  type: "Case" | "Statute" | "Regulation" | "Person" | "Organization" | "LegalConcept" | "Jurisdiction"
  details?: string | null
  
}

export interface LegalQueryAnalysis {
  reasoning: DetailedReasoning
  search_queries: SearchQueryItem[]
  
}

export interface LegalReportSection {
  section_title: string
  content: string
  
}

export interface OverallSynthesis {
  key_synthesized_topics: SynthesizedTopic[]
  unanswered_aspects?: string[] | null
  emerging_questions?: string[] | null
  reasoning: DetailedReasoning
  
}

export interface ReasoningStep {
  summary: string
  items_considered?: string[] | null
  
}

export interface ResearchAssessment {
  is_sufficient: boolean
  assessment_summary: string
  identified_gaps?: string[] | null
  next_action: NextActionType
  suggested_queries_for_refinement?: SearchQueryItem[] | null
  document_ids_for_deeper_analysis?: string[] | null
  reasoning: DetailedReasoning
  
}

export interface SearchQueryItem {
  query_string: string
  expected_information: string[]
  
}

export interface SearchResultItem {
  id: string
  url: string
  title?: string | null
  source_name: string
  snippet?: string | null
  full_text?: string | null
  published_date?: string | null
  retrieval_date: string
  author?: string | null
  score?: number | null
  original_query?: SearchQueryItem | null
  metadata?: Record<string, string> | null
  
}

export interface SynthesizedTopic {
  topic_title: string
  synthesis: string
  supporting_document_ids: string[]
  confidence_score: number
  
}
